service: push-notification
useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-2
  timeout: 10
  memorySize: 512

functions:
  PushNotification:
    handler: src/app.lambdaHandler
    events:
      - http:
          method: post
          path: /notification

  OnboardUser:
    handler: src/app.onboardHandler
    environment:
      USER_TABLE_NAME: users
      DEVICE_TABLE_NAME: devices
    events:
      - http:
          method: post
          path: /onboard