AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  push-notification-lambda  
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  PushNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageUri: 00000000000.dkr.ecr.ap-southeast-2.amazonaws.com/push-notification:latest
      Events:
        PushNotification:
          Type: Api
          Properties:
            Path: /notification
            Method: post
    Metadata:
      DockerTag: nodejs16.x-v1
      DockerContext: ./src
      Dockerfile: Dockerfile

Outputs:
  PushNotificationApi:
    Description: "API Gateway endpoint URL for Prod stage for PushNotification function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notification/"
  PushNotificationFunction:
    Description: "PushNotification Lambda Function ARN"
    Value: !GetAtt PushNotificationFunction.Arn
  PushNotificationFunctionIamRole:
    Description: "Implicit IAM Role created for PushNotification function"
    Value: !GetAtt PushNotificationFunctionRole.Arn
